---
title: "Mini-Project 2"
author: "Dejia Tang, Zicong Wei"
date: "October 31, 2017"
output: html_document
---

```{r message=FALSE, echo=FALSE, warning=FALSE}
library(tidyverse)
library(ggthemes)
library(ggrepel)
```

```{r, echo=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

## Data Wrangling
```{r message=FALSE, echo=TRUE, warning=FALSE}
candidates <- candidates %>%
  left_join(house_elections, by=c('cand_id' = 'fec_id' ))

df_candidate <- candidates %>%
  mutate(type = ifelse(cand_party_affiliation == 'DEM', ifelse(ge_winner == 'W', 'dem_w', 'dem_nw'),ifelse(ge_winner == 'W', 'rep_w', 'rep_nw'))) %>%
  filter(!is.na(type)) %>%
  select(cand_id, type)

glimpse(df_candidate)

df_contributions <- contributions %>%
  left_join(committees, by='cmte_id') %>%
  select(cmte_id, transaction_type, transaction_amt, cand_id.x, org_type)

glimpse(df_contributions)


df1 <- df_candidate %>%
  left_join(df_contributions, by=c('cand_id' = 'cand_id.x' )) %>%
  arrange(cand_id) %>%
  filter(!is.na(transaction_type), !is.na(org_type), org_type !='', transaction_type!='24K', transaction_type!='24C') %>%
  group_by(type, transaction_type) %>%
  summarize(type_amt = sum(transaction_amt))

df2 <- df_candidate %>%
  left_join(df_contributions, by=c('cand_id' = 'cand_id.x' )) %>%
  arrange(cand_id) %>%
  filter(!is.na(transaction_type), !is.na(org_type), org_type !='', transaction_type!='24K') %>%
  filter(org_type!="V", org_type!="W") %>%
  group_by(type, org_type) %>%
  summarize(type_amt = sum(transaction_amt))
```

## Creating Plots
```{r message=FALSE, echo=TRUE, warning=FALSE}
my_plot <- df1 %>%
  ggplot(aes(x = transaction_type, y = type_amt, fill= type)) +
  geom_bar(stat="identity", position='fill', alpha=0.8)

my_plot2 <- df1 %>%
  ggplot(aes(x = type, y = type_amt, fill= transaction_type)) +
  geom_bar(stat="identity", position='fill', alpha=0.8) +
  scale_fill_brewer(
  	palette = "Paired",
  	name = "Transaction Type",
  	labels = c("Independent expenditure\nopposing election", "Independent expenditure\nadvocating election", "Communication\ncost", "Communication\ncost against", "In-kind contribution made\nto registered filer")) +
  scale_x_discrete(labels = c("Democrat\nNot Elected","Democrat\nElected","Republican\nNot Elected","Republican\nElected")) +
  scale_y_continuous(
    breaks = c(0, 0.25, 0.5, 0.75, 1),
    labels = c('0%', '25%', '50%','75%',  '100%'),
    expand = c(0, 0)
  ) +
  theme_fivethirtyeight() +
  theme(panel.border = element_blank(), axis.title = element_blank()) +
  ggtitle("Distribution of Types of Contributions\nin Election Campaign")

my_plot3 <- df2 %>%
  ggplot(aes(x = org_type, y = type_amt, fill= type)) +
  geom_bar(stat="identity", position='fill', alpha=0.8)

my_plot4 <- df2 %>%
  ggplot(aes(x = type, y = type_amt, fill= org_type)) +
  geom_bar(stat="identity", position='fill', alpha=0.8) +
  scale_x_discrete(labels = c("Democrat\nNot Elected","Democrat\nElected","Republican\nNot Elected","Republican\nElected")) +
  scale_y_continuous(
    breaks = c(0, 0.25, 0.5, 0.75, 1),
    labels = c('0%', '25%', '50%','75%',  '100%'),
    expand = c(0, 0)
  ) +
  theme_fivethirtyeight() +
  theme(panel.border = element_blank(), axis.title = element_blank()) +
  scale_fill_manual(
  	values = c("#f7c143", "#556eed", "#f2763c", "#a5a5a5"),
  	name = "Organization Type",
  	labels = c("Corporation", "Labor organization", "Membership organization", "Trade association")) +
  ggtitle("Distribution of Interest Groups behind Contributions\nin Election Campaign")
```
## Present Plots
```{r message=FALSE, echo=TRUE, warning=FALSE, fig.align="center", fig.width=10, fig.height=6.5}
my_plot2
my_plot4
```
